### PR TITLE
feat(network): add VPN functionality

### PR DESCRIPTION
**Pull request by tyrypyrking**

### CODE REVIEW

**Review by linkfrg — CHANGES_REQUESTED** [review]
ignis/services/network/vpn.py
```python
    @GObject.Property
    def get_id(self) -> str | None:
        return self._connection.get_id()
```
Why the name of this property starts from ``get_``? This is usually what methods are called. I think it's better to rename it to just ``id``.

In ignis/services/network/__init__.py also add ``Vpn`` class itself to ``__all__``.

You also forgot to mention it in ``NetworkService`` docstring, in Properties section.

ignis/services/network/vpn.py
```python
def toggle_connection(self) -> None:
        if self.is_connected:
            self.disconnect_from()
        else:
            self.connect_to()
```
Please add docstring for this method

**Comment by tyrypyrking** [comment]
> ignis/services/network/vpn.py
> 
> ```python
>     @GObject.Property
>     def get_id(self) -> str | None:
>         return self._connection.get_id()
> ```
> 
> * Why the name of this property starts from `get_`? This is usually what methods are called. I think it's better to rename it to just `id` or `connection_id`.


Renamed to connection_id, but thinking back, other objects use `name()` method, while it's not representative of it's inner workings it's more uniform with the outside.

**Comment by linkfrg** [comment]
> Renamed to connection_id, but thinking back, other objects use `name()` method, while it's not representative of it's inner workings it's more uniform with the outside.

What I'm saying is that the property name starts with ``get_``, it's confusing because property names never start with that prefix.

**Comment by linkfrg** [comment]
To make docstrings visible in docs, add newly added classes to ``docs/api/services/network.rst``, e.g.:
```rst
.. autoclass:: ignis.services.network.Vpn
    :members:

.. autoclass:: ignis.services.network.VpnConnection
    :members:
```
Btw also run Ruff (check & format)

**Review by linkfrg — CHANGES_REQUESTED** [review]
In general everything is ok, but there are some corrections:
ignis/services/network/vpn.py
```python
from ignis.services.network._imports import NM
```
It's better to use relative import:
```python
from ._imports import NM
```

ignis/services/network/vpn.py
```python
- **active_vpn_id** (``str``, read-only): The id (name) of the first active vpn connection.
```
Here is incorrect type for this property in docstring, according to your code it should be ``str | None``

**Review by linkfrg — APPROVED** [review]
Thanks!

**Pull request merged**
