### PR TITLE
feat: Brightness(Backlight) Service

### PR DESCRIPTION
**Pull request by gauravsatish**
I made this for my laptop for brightness controls and thought why not make a PR.
The docs are missing, but if at all you decide you want to merge this, then i can write up the docs

Essentially, this service introduces 3 GObject properties:
1. **max_brightness:**
- Reads maximum allowed backlight value from `/sys/class/<your-device-backlight>/max_brightness`;
- -1 if not applicable
2. **brightness:**
- Stores current brightness set by the system
- Getter and Setter methods, the setter correspondingly calls the DBus method to actually change the brightness
- -1 if not applicable
3. **active:**
- True if a backlight if found in `/sys/class/`
- No operation is conducted if `active` is not True

all mypy and ruff checks pass

this now lets me add for example this slider i basically cloned from the audio slider in your dotfiles but for brightness:

2024-10-10T00:25:56,910958596+05:30

### CODE REVIEW

**Comment by linkfrg** [comment]
Thanks for this PR!
1. I will merge it, so you can write up a docs
2. I think it’s worth renaming ``active`` property to ``available``, for clarity

**Comment by linkfrg** [comment]
```
sessionidcmd = exec_sh("echo $XDG_SESSION_ID")
        try:
            sessionidcmd.check_returncode()
            sessionid = str(sessionidcmd.stdout)
        except CalledProcessError:
            logger.error("Failed to get session id. Brightness support disabled")
            self._active = False
            return ""
```
Here it is better to use ``os.getenv()`` to get the ``XDG_SESSION_ID`` environment variable

**Comment by linkfrg** [comment]
in ``__init__``:
```python
with open(
                        "/sys/class/backlight/" + backlight + "/brightness"
                    ) as brightness_file:
                        self._brightness = int(brightness_file.read().strip())
```
repeating code defined in ``__update_brightness()``, it's better to call this function during init

**Comment by linkfrg** [comment]
```python
logger.warning("Backlight not found. Brightness support disabled.")
```
remove these warnings, there is already ``active`` (``available``) property to indicate that backlight is not found

**Comment by gauravsatish** [comment]
thanks for the feedback, will do. Should be done by maybe tomorrow

**Comment by linkfrg** [comment]
```python
    def __update_from_file(self, file: Literal["brightness", "max_brightness"], notify: bool) -> None:
        if self._available:
            with open(f"/sys/class/backlight/{self._backlight}/{str(file)}") as backlight_file:
```

```python
/{self._backlight}/{str(file)}")
```
Converting string to... string

**Comment by gauravsatish** [comment]
Yeah mypy was doing some weird stuff
That was not my original version 
It was complaining about something to do with the`Literal` type

**Comment by gauravsatish** [comment]
And another thing, I wrote up the docs, but running `make html` does not create backlightservice.HTML
Is there anything I need to do other than just write the docstring?

**Comment by linkfrg** [comment]
> And one other thing, if you know a way to do assignment operations in lambda funcs, that last function will become so much more cleaner

You can use ``setattr()`` method, like ``setattr(OBJECT, PROP_NAME, NEW_VALUE)``

**Comment by gauravsatish** [comment]
The docs look like this: 

2024-10-10T15:29:41,651129143+05:30

any changes needed?

**Comment by linkfrg** [comment]
> any changes needed?

I think no, If any edits are needed, I will do them myself

So, thanks for this PR! Merging

**Pull request merged**
