### PR TITLE
fix(upower): properties are not notified in UPowerDevice

### LINKED ISSUE #24: Battery bar does not update
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Related to dotfiles ? *

- [X] I'm sure the problem is related specifically to Ignis.

### Regression?

No

### Version

Ignis 0.2.dev0
Branch: main
Commit: 424689830e89844abb0d95991e098ad0480a55ae (feat: add UPower Service (#10))

### Distro

Arch Linux x86_64

### Description

Battery percentage does not change after startup and remains frozen. 
I suspect this might be due to the file ~/.config/ignis/services/upower.py not existing.

### How to reproduce

Have the latest dotfiles install along with all said dependencies and do something to let the battery status change (ex:discharge), the ignis bar battery widget does not reflect updated change.

### Logs, images, videos, config files, CSS/SCSS files

_No response_

### PR DESCRIPTION
**Pull request by linkfrg**
Looks like ``UPowerGlib`` doesn't automatically notify properties of ``UPowerGlib.Device``.
So, it is necessary to use D-Bus directly and connect to D-Bus signals.
Closes #24.

There are some little breaking changes:
- nuke ``UPowerNotFoundError``, add ``UPowerNotRunningError`` instead
- nuke ``device`` property in ``UPowerDevice``, add ``object_path`` and ``proxy`` properties.

The rest of the API remained the same.

- [ ] Testing

### CODE REVIEW

**Comment by linkfrg** [comment]
@gauravsatish oh i forgot to add watching for "IconName" property.
Should be fixed in [0d374f8](https://github.com/linkfrg/ignis/pull/26/commits/0d374f8f357035a416c115fe7f288a7ad3ae84fa)

**Comment by gauravsatish** [comment]
I've tested it, and i can confirm that the icon and percentage is being updated.

**Comment by linkfrg** [comment]
> I've tested it, and i can confirm that the icon and percentage is being updated.

Ok, now I'm waiting for the issue author (#24) to test it and then merge

**Comment by linkfrg** [comment]
> Ok, now I'm waiting for the issue author (#24) to test it and then merge

Okay, I think one confirmation is enough. Merging

**Pull request merged**
