### PR TITLE
Build nix package from repository source

### PR DESCRIPTION
**Pull request by ratson**
- Move nix files to `nix/`
- Set nix package `src` to use repository
- Set `mainProgram` instead of `main_program`
- Set `version` to include commit short hash and modified date

### CODE REVIEW

**Review by linkfrg — CHANGES_REQUESTED** [review]
[docs/user/installation.rst](https://github.com/linkfrg/ignis/pull/25/files#diff-42ef85ce47509c8412d1438e9ca4b556b2f519aa95d9149f76b75a09587ecb42)
```nix
ignis.url = "git+https://github.com/linkfrg/ignis?submodules=1";
```
I'm a bit confused by this line. Is it possible to fetch submodules in ``ignis.nix`` as it is now?

**Comment by ratson** [comment]
> Is it possible to fetch submodules in `ignis.nix` as it is now?

No, the following command gives the error `meson.build:31:0: ERROR: Neither a subproject directory nor a gvc.wrap file was found.`,

```sh
nix build "github:ratson/ignis/a1ea09b19302944cbf7137e89dddc80f58fa3c47"
```

while the follow command builds without problem,

```sh
nix build "git+https://github.com/ratson/ignis?submodules=1&rev=a1ea09b19302944cbf7137e89dddc80f58fa3c47"
```

**Review by linkfrg — APPROVED** [review]
I'm just a little scared by the length of this line in the docs, in ags for example Gvc fetch manually in ``default.nix``.
Anyway, thanks!

Btw you also need to make a PR for the ``stable`` branch to update the stable docs.

**Comment by ratson** [comment]
Hyprland build from the GitHub repository requires [the same](https://github.com/hyprwm/Hyprland/issues/5891#issuecomment-2094865630), so it should be fine.

Here why `github:` not working for git submodule: https://github.com/NixOS/nix/issues/4423#issuecomment-1580924502

**Pull request merged**
