### PR TITLE
feat: add UPower Service

### PR DESCRIPTION
**Pull request by linkfrg**
Add ~~battery~~ UPower Service.
~~Completely stolen from [AGS](https://github.com/Aylur/ags/blob/main/src/service/battery.ts)~~ (Now it's 100% Ignis implementation)
I don't have a device with a battery, so this pull request requires testing by other people.

- [x] Testing
- [x] Documentation
- [ ] Charge Threshold support
- [x] Multiple batteries support
- [x] Move to UPowerGlib

How to install:
1. [Set up a development environment](https://linkfrg.github.io/ignis/latest/dev/env.html)
2. ``git checkout feat/battery``. 
On each new commit use ``git pull`` to receive new changes

### CODE REVIEW

**Comment by Munseer-am** [comment]
> Add battery service. Completely stolen from [AGS](https://github.com/Aylur/ags/blob/main/src/service/battery.ts) I don't have a device with a battery, so this pull request requires testing by other people.
> 
> * [ ]  Testing

I will help out with testing when I can!

**Comment by linkfrg** [comment]
this terrible code can help you with testing:
```python
from ignis.services.battery import BatteryService

battery = BatteryService.get_default()

for prop_name in [
    "available",
    "percent",
    "charging",
    "charged",
    "icon_name",
    "time_remaining",
    "energy",
    "energy_full",
    "energy_rate",
]:
    battery.connect(
        f"notify::{prop_name.replace('_', '-')}",
        lambda x, y: print(f"{prop_name}: ", getattr(battery, prop_name)),
    )
```

**Comment by Munseer-am** [comment]
Issue: I am encountering an error when running the `ignis init --debug.`

`ignis.exceptions.AnotherNotificationDaemonRunningError: Another notification daemon is already running: SwayNotificationCenter`

**Comment by linkfrg** [comment]
This is not an issue, this exception means that you have another notification daemon running. In your case it is swaync, kill or remove it

**Comment by Munseer-am** [comment]
```
from ignis.services.battery import BatteryService

battery = BatteryService.get_default()

print(battery.available)
```
it is returning False

**Comment by linkfrg** [comment]
try now (after [87ea7d9](https://github.com/linkfrg/ignis/pull/10/commits/87ea7d9b72cbd1172542c084c0ebec2cd5300030))

**Comment by CGod-dev** [comment]
> I don't have a device with a battery, so this pull request requires testing by other people.

```bash
sudo udevadm trigger --subsystem-match=power_supply --action=add
```

**Comment by linkfrg** [comment]
> ```shell
> sudo udevadm trigger --subsystem-match=power_supply --action=add
> ```

nothing changed

**Comment by Munseer-am** [comment]
> try now (after [87ea7d9](https://github.com/linkfrg/ignis/pull/10/commits/87ea7d9b72cbd1172542c084c0ebec2cd5300030))

Nothing has changed and it has a new error
```
battery = BatteryService.get_default()
Error while fetching Present property: 'DBusProxy' object has no attribute 'Present'
None
```

**Comment by CGod-dev** [comment]
> > ```shell
> > sudo udevadm trigger --subsystem-match=power_supply --action=add
> > ```
> 
> nothing changed

You can "simulate" a battery by using symlink
```bash
mkdir BAT0
sudo ln -s /sys/class/power_supply/BAT0 BAT0/
echo 100 | sudo tee BAT0/capacity
echo "Charging" | sudo tee BAT0/status
echo 4200000 | sudo tee /BAT0/voltage_now
echo 5000000 | sudo tee /BAT0/current_now
```

**Comment by linkfrg** [comment]
> > try now (after [87ea7d9](https://github.com/linkfrg/ignis/pull/10/commits/87ea7d9b72cbd1172542c084c0ebec2cd5300030))
> 
> it is still returning False and it has a new error
> 
> ```
> battery = BatteryService.get_default()
> Error while fetching Present property: 'DBusProxy' object has no attribute 'Present'
> None
> ```

Have you installed ``upower``?

**Comment by CGod-dev** [comment]
Being able to set a charge limit from the quick settings would be nice too, somewhat like this [gnome extension](https://github.com/maniacx/Battery-Health-Charging)

**Comment by linkfrg** [comment]
> > > ```shell
> > > sudo udevadm trigger --subsystem-match=power_supply --action=add
> > > ```
> > 
> > 
> > nothing changed
> 
> You can "simulate" a battery by using symlink
> 
> ```shell
> mkdir BAT0
> sudo ln -s BAT0/ /sys/class/power_supply/BAT0/
> echo 100 | sudo tee BAT0/capacity
> echo "Charging" | sudo tee BAT0/status
> echo 4200000 | sudo tee BAT0/voltage_now
> echo 5000000 | sudo tee BAT0/current_now
> ```
> 
> Although, this method is ancient. I don't know if it will work on modern linux

It seems that /sys cannot be modified. But I found some [kernel module](https://github.com/hoelzro/linux-fake-battery-module) and it's working

**Comment by CGod-dev** [comment]
> this terrible code can help you with testing:
> 
> ```python
> from ignis.services.battery import BatteryService
> 
> battery = BatteryService.get_default()
> 
> for prop_name in [
>     "available",
>     "percent",
>     "charging",
>     "charged",
>     "icon_name",
>     "time_remaining",
>     "energy",
>     "energy_full",
>     "energy_rate",
> ]:
>     battery.connect(
>         f"notify::{prop_name.replace('_', '-')}",
>         lambda x, y: print(f"{prop_name}: ", getattr(battery, prop_name)),
>     )
> ```

Finally got the pull request working. Here's the output (Battery is at 98 and AC is plugged in)

```
2024-10-04 19:03:15 [INFO] Using configuration file: /home/matt/.config/ignis/config.py
2024-10-04 19:03:15 [INFO] Applied css: /home/matt/.config/ignis/style.scss
2024-10-04 19:03:15 [INFO] Ready.
energy_rate:  0.0
```

**Comment by linkfrg** [comment]
D-Bus proxy could not update properties because it was looking for the name in the current session bus, not in the system one. Should be fixed after [4f09d4a](https://github.com/linkfrg/ignis/pull/10/commits/4f09d4a30336be58bdfb90a3636360477238b6fd)

**Comment by dylanc24** [comment]
If I was smarter, I would test before It get push... But here I am, too stupid to uninstall and rebuild the package, hoping it come soon. .

**Comment by CGod-dev** [comment]
> D-Bus proxy could not update properties because it was looking for the name in the current session bus, not in the system one. Should be fixed after [4f09d4a](https://github.com/linkfrg/ignis/pull/10/commits/4f09d4a30336be58bdfb90a3636360477238b6fd)
> 
> Edit: strange but `available` is still `False` Edit 2: This is because `self._available` never set to `True` in `self.__sync` [d426567](https://github.com/linkfrg/ignis/pull/10/commits/d426567c3bf3616266d10df6fd20709f3bac0055)

```
nergy_rate:  7.404
energy_rate:  7.404
energy_rate:  7.404
energy_rate:  7.404
energy_rate:  7.404
energy_rate:  7.404
energy_rate:  10.605
energy_rate:  10.605
energy_rate:  10.605
energy_rate:  10.605
energy_rate:  10.605
energy_rate:  10.605
energy_rate:  10.605
energy_rate:  10.605
energy_rate:  10.605
```
Looks to be working now. Can you provide instructions for fast rebuilding and installing? I am not very familiar with meson or python

**Comment by linkfrg** [comment]
> If I was smarter, I would test before It get push... But here I am, too stupid to uninstall and rebuild the package, hoping it come soon. .

You can [Set up a development environment](https://linkfrg.github.io/ignis/latest/dev/env.html) and when:
```git checkout feat/battery```. On each new commit use ``git pull`` to receive new changes

**Comment by linkfrg** [comment]
> Can you provide instructions for fast rebuilding and installing? I am not very familiar with meson or python

Added instruction in the first message

**Comment by linkfrg** [comment]
> > > Can you provide instructions for fast rebuilding and installing? I am not very familiar with meson or python
> > 
> > 
> > Added instruction in the first message
> 
> I know how to use git. Just can't get meson to see the changes
> 
> ```shell
> meson compile -C build
> ```
> 
> ```
> INFO: autodetecting backend as ninja
> INFO: calculating backend command to run: /sbin/ninja -C /redacted/for/privacy/ignis/build
> ninja: Entering directory `/redacted/for/privacy/ignis/build'
> ninja: no work to do.
> ```

You don't need to rebuild Ignis every time. You need to do this in the first time to build submodules and install bin file. Since we are making a symbolic link in the above tutorial, we don't need to reinstall Ignis every time to update it in venv.

**Comment by linkfrg** [comment]
> Being able to set a charge limit from the quick settings would be nice too, somewhat like this [gnome extension](https://github.com/maniacx/Battery-Health-Charging)

added to tasks

**Comment by dylanc24** [comment]
The service seems to work , i just need to find how to properly implement that in my bar.

**Comment by linkfrg** [comment]
Added support for charge threshold, need testing.
There are 4 new properties:
- charge_threshold (bool)
- charge_threshold_supported (bool)
- charge_start_threshold (str)
- charge_end_threshold (str)

**Comment by CGod-dev** [comment]
Issue: The service seems to get confused when there is 2 batteries, see below:
```
energy_rate:  10.204
energy_rate:  0
energy_rate:  10.204
energy_rate:  0
energy_rate:  10.204
energy_rate:  0
energy_rate:  10.204
energy_rate:  0
energy_rate:  10.204
energy_rate:  0
```

**Comment by CGod-dev** [comment]
> * charge_threshold (bool)
> * charge_threshold_supported (bool)

The bools seem to work. But I couldn't get the strings to display anything other than ``None``.

**Comment by linkfrg** [comment]
> Issue: The service seems to get confused when there is 2 batteries, see below:
> 
> ```
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> ```
> 
> Edit: Thinkpads have 2 batteries, one being internal and one being external; `/sys/class/power_supply/BAT0` and `/sys/class/power_supply/BAT1` in order.

strange, ``/org/freedesktop/UPower/devices/DisplayDevice`` should indicate the battery dedicated to display (the main battery).

Seems like we need support for managing multiple batteries

**Comment by linkfrg** [comment]
> Typo?
> 
> > * charge_start_threshold (str)
> >   def charge_start_threshold(self) -> int:
> > * charge_end_threshold (str)
> >   def charge_end_threshold(self) -> int:

oops, yes

**Comment by linkfrg** [comment]
> Issue: The service seems to get confused when there is 2 batteries, see below:
> 
> ```
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> energy_rate:  10.204
> energy_rate:  0
> ```
> 
> Edit: Thinkpads have 2 batteries, one being internal and one being external; `/sys/class/power_supply/BAT0` and `/sys/class/power_supply/BAT1` in order.

Only the energy_rate values ​​differ?

From upower docs:
> Amount of energy being drained from the source, measured in W. If positive, the source is being discharged, if negative it's being charged. 

Maybe the power consumption is just not constant, so it drops to zero and rises back to 10.204

**Comment by Munseer-am** [comment]
The battery percentage displays correctly, and I have implemented the battery in the bar, but battery.charged and battery.charging don't seem to work properly; both return False, even though the upower command shows that the battery state is charging.

**Comment by linkfrg** [comment]
[9caa6b4](https://github.com/linkfrg/ignis/pull/10/commits/9caa6b45c2640f502208c5d9460cb196435fab5e): Moved to UPowerGlib, also added support for managing multiple batteries, need testing.

**Comment by artinmare** [comment]
Hi, sorry I'm new to Linux and git in general so please pardon my clumsiness

First of all, love the work, I have been testing this and it seems to work fine for me. My laptop only have a single battery so cannot test for the multiple one, but everything else seems to be good

The only problem i found is the time_remaining prop which failed cause there is no `self._charging ` attribute in Battery class. It seems to be a typo, I got it working by changing the `self._charging` to `self.charging` in the `time_remaining` function line 96 in the battery.py file.

Didn't know how to make a pull request so that's about it. I would report if I found another issues, love my experience with this software so far, thank you for creating it.

**Comment by linkfrg** [comment]
> The only problem i found is the time_remaining prop which failed cause there is no `self._charging ` attribute in Battery class. It seems to be a typo, I got it working by changing the `self._charging` to `self.charging` in the `time_remaining` function line 96 in the battery.py file.

fixed in [faf4e41](https://github.com/linkfrg/ignis/pull/10/commits/faf4e41e82428b1bbb131440baefdb982682579c)

**Comment by linkfrg** [comment]
[56ac88d](https://github.com/linkfrg/ignis/pull/10/commits/56ac88d4dd11644644c51f2f9393e0b07d6d85ae)
BREAKING CHANGE: ``BatteryService`` renamed to ``UPowerService``.

Now this service has support for non battery devices.

In particular, batteries have been moved to the new property: ``batteries``.

**Comment by linkfrg** [comment]
The only thing left is to test charge threshold

**Pull request merged**
